language: python

python:
  - 3.6

sudo: required

services:
  - docker

install:
  - make build
  - make build27

script:
  - make tests
  - make tests27
  - make docs
  - make lint-pylint || true
  - make lint-yapf
  - ./scripts/checkversion.sh

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        make publish;
    fi

notifications:
  email: false
